# Generated by Django 5.2.4 on 2025-07-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='02D0E0', max_length=10, unique=True),
        ),
    ]
